version: '3'
services:
  server:
   image: coreoasis/api_server:1.15.6
   ports:
     - 8000:8000
   links:
     - server-db
     - celery-db
     - rabbit
   environment:
     - OASIS_ADMIN_USER=admin
     - OASIS_ADMIN_PASS=password 
     - OASIS_DEBUG=1
     - OASIS_RABBIT_HOST=rabbit
     - OASIS_RABBIT_PORT=5672
     - OASIS_RABBIT_USER=rabbit
     - OASIS_RABBIT_PASS=rabbit
     - OASIS_SERVER_DB_HOST=server-db
     - OASIS_SERVER_DB_PASS=oasis
     - OASIS_SERVER_DB_USER=oasis
     - OASIS_SERVER_DB_NAME=oasis
     - OASIS_SERVER_DB_PORT=3306
     - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_CELERY_DB_HOST=celery-db
     - OASIS_CELERY_DB_PASS=password
     - OASIS_CELERY_DB_USER=celery
     - OASIS_CELERY_DB_NAME=celery
     - OASIS_CELERY_DB_PORT=3306
     - STARTUP_RUN_MIGRATIONS=true
   volumes:
     - ${OASIS_MEDIA_ROOT:-/tmp/docker-shared-fs}:/shared-fs:rw
  worker-monitor:
   image: coreoasis/api_server:1.15.6
   command: [wait-for-server, 'server:8000', celery, -A, src.server.oasisapi, worker, --loglevel=INFO]
   links:
     - server-db
     - celery-db
     - rabbit
   environment:
     - OASIS_DEBUG=1
     - OASIS_RABBIT_HOST=rabbit
     - OASIS_RABBIT_PORT=5672
     - OASIS_RABBIT_USER=rabbit
     - OASIS_RABBIT_PASS=rabbit
     - OASIS_SERVER_DB_HOST=server-db
     - OASIS_SERVER_DB_PASS=oasis
     - OASIS_SERVER_DB_USER=oasis
     - OASIS_SERVER_DB_NAME=oasis
     - OASIS_SERVER_DB_PORT=3306
     - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_CELERY_DB_HOST=celery-db
     - OASIS_CELERY_DB_PASS=password
     - OASIS_CELERY_DB_USER=celery
     - OASIS_CELERY_DB_NAME=celery
     - OASIS_CELERY_DB_PORT=3306
   volumes:
     - ${OASIS_MEDIA_ROOT:-/tmp/docker-shared-fs}:/shared-fs:rw
  worker:
    image: ern_worker_image:1.15.8
    links:
     - celery-db
     - rabbit:myrabbit
    environment:
     - OASIS_MODEL_SUPPLIER_ID=ERN
     - OASIS_MODEL_ID=PanEuropeanQuake
     - OASIS_MODEL_VERSION_ID=1
     - OASIS_RABBIT_HOST=rabbit
     - OASIS_RABBIT_PORT=5672
     - OASIS_RABBIT_USER=rabbit
     - OASIS_RABBIT_PASS=rabbit
     - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_CELERY_DB_HOST=celery-db
     - OASIS_CELERY_DB_PASS=password
     - OASIS_CELERY_DB_USER=celery
     - OASIS_CELERY_DB_NAME=celery
     - OASIS_CELERY_DB_PORT=3306
     - OASIS_OASISLMF_CONFIG=/home/worker/oasislmf.json
     - OASIS_KEEP_RUN_DIR=True
     - KTOOLS_LEGACY_GUL_STREAM=False
     - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    volumes:
     #- ./:/var/oasis/:rw
     - ${OASIS_MEDIA_ROOT:-/tmp/docker-shared-fs}:/shared-fs:rw
     - ./model_data:/var/oasis/model_data:rw
     - ./keys_data:/var/oasis/keys_data:rw
  server-db:
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=oasis
      - MYSQL_PASSWORD=oasis
      - MYSQL_DATABASE=oasis
    volumes:
      - ${OASIS_DOCKER_DB_DATA_DIR:-/tmp/db-data}/server:/var/lib/mysql/:rw
  celery-db:
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=celery
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=celery
    volumes:
      - ${OASIS_DOCKER_DB_DATA_DIR:-/tmp/db-data}/celery:/var/lib/mysql/:rw
  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - 5672:5672
      - 15672:15672
  flower:
    image: iserko/docker-celery-flower 
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://rabbit:rabbit@rabbit:5672
    entrypoint:
      - flower 
      - --port=5555 
      - --broker_api=http://rabbit:rabbit@rabbit:15672/api/
    links:
     - celery-db
     - rabbit
